name: Run Telegram Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # امکان اجرای دستی
  schedule:
    - cron: '*/5 * * * *' # اجرای هر 5 دقیقه برای فعال نگه داشتن ربات

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytelegrambotapi python-dotenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Telegram Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: python main.py
